fresh_calc_homepage:
    path:     /
    defaults: { _controller: FreshCalcBundle:Index:index }
    requirements:
        methods:  GET

get_parameters:
    path:     /parameter/{id}
    defaults: { _controller: FreshCalcBundle:Index:showParameters }
    requirements:
        methods:  GET
        id: \d+

fresh_calc_generate_pdf:
    path:     /generate_pdf
    defaults: { _controller: FreshCalcBundle:Index:generatePdf }
    requirements:
        methods:  POST