<?php

namespace Fresh\CalcBundle\Entity\Repository;

/**
 * ParametersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametersRepository extends \Doctrine\ORM\EntityRepository
{
    public function getParametersForSiteType($siteTypeId)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.sites_types = :site_type_id')
            ->setParameter('site_type_id', $siteTypeId);

        return $qb->getQuery()
            ->getResult();
    }
}
