<?php

namespace Fresh\CalcBundle\Entity\Repository;

use Doctrine\ORM\Query;
/**
 * ParametersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametersRepository extends \Doctrine\ORM\EntityRepository
{
    public function getParametersForSiteType($siteTypeId)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.sites_types = :site_type_id')
            ->setParameter('site_type_id', $siteTypeId);

        return $qb->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);
    }

    public function getParametersByIds( $parametersIds=[] )
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.id IN (:parametersIds)')
            ->setParameter('parametersIds', $parametersIds);


        return $qb->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);
    }
}
