<?php

namespace Fresh\CalcBundle\Entity\Repository;

/**
 * SitesTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitesTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
