<?php

namespace Fresh\CalcBundle\Entity\Repository;

/**
 * WorkTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
