fresh_patenting:
    resource: "@FreshPatentingBundle/Resources/config/routing.yml"
    prefix:   /patenting

fresh_calc:
    resource: "@FreshCalcBundle/Resources/config/routing.yml"
    prefix:   /

