<?php

namespace Fresh\PatentingBundle\Entity\Repository;

use Doctrine\ORM\Query;
/**
 * ContractsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractsRepository extends \Doctrine\ORM\EntityRepository
{

    public function getMaxId()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('MAX(u.id)');
        return $qb->getQuery()->getSingleResult();
    }

}
