<?php

namespace Fresh\PatentingBundle\Entity\Repository;

use Doctrine\ORM\Query;
/**
 * LegalEntitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegalEntitiesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOrganizations($organizationType)
    {

        $qb = $this->createQueryBuilder('c')
            ->select('c')->where('c.isSelfOrganization = 0');

        if ( $organizationType == 0 ) {
            $qb->andWhere('c.organizationType = :organizationType')
                ->setParameter('organizationType', $organizationType);
        } else {
            $qb->andWhere('c.organizationType != 0');
        }

        return $qb->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);
    }

}
