<?php

namespace Fresh\PatentingBundle\Entity\Repository;

use Doctrine\ORM\Query;
/**
 * PatentingPricesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatentingPricesRepository extends \Doctrine\ORM\EntityRepository
{


}
